export const factoryAbi = [
  {
    type: "function",
    name: "createLaunch",
    stateMutability: "nonpayable",
    inputs: [
      { name: "name_", type: "string" },
      { name: "symbol_", type: "string" },
      { name: "totalSupply_", type: "uint256" },
      { name: "metadataURI_", type: "string" },
    ],
    outputs: [
      { name: "launchAddress", type: "address" },
      { name: "tokenAddress", type: "address" },
    ],
  },
  {
    type: "function",
    name: "launchCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "launches",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "virtualUsdcReserve",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "event",
    name: "LaunchCreated",
    anonymous: false,
    inputs: [
      { indexed: true, name: "index", type: "uint256" },
      { indexed: true, name: "creator", type: "address" },
      { indexed: true, name: "launch", type: "address" },
      { indexed: false, name: "token", type: "address" },
      { indexed: false, name: "name", type: "string" },
      { indexed: false, name: "symbol", type: "string" },
      { indexed: false, name: "totalSupply", type: "uint256" },
      { indexed: false, name: "metadataURI", type: "string" },
    ],
  },
] as const;

export const launchAbi = [
  {
    type: "function",
    name: "token",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "creator",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "protocolTreasury",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "creatorFeesAccrued",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "protocolFeesAccrued",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "metadataURI",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "totalSupply",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getBuyQuote",
    stateMutability: "view",
    inputs: [{ name: "grossUsdcIn", type: "uint256" }],
    outputs: [
      { name: "tokenOut", type: "uint256" },
      { name: "netUsdcIn", type: "uint256" },
      { name: "creatorFee", type: "uint256" },
      { name: "protocolFee", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getSellQuote",
    stateMutability: "view",
    inputs: [{ name: "tokenIn", type: "uint256" }],
    outputs: [
      { name: "netUsdcOut", type: "uint256" },
      { name: "grossUsdcOut", type: "uint256" },
      { name: "creatorFee", type: "uint256" },
      { name: "protocolFee", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "marketState",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "tokenReserve_", type: "uint256" },
      { name: "realUsdcReserve_", type: "uint256" },
      { name: "curveUsdcReserve_", type: "uint256" },
      { name: "circulatingSupply_", type: "uint256" },
      { name: "spotPriceE18_", type: "uint256" },
      { name: "marketCapE18_", type: "uint256" },
      { name: "progressBps_", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "buy",
    stateMutability: "nonpayable",
    inputs: [
      { name: "usdcIn", type: "uint256" },
      { name: "minTokenOut", type: "uint256" },
      { name: "recipient", type: "address" },
      { name: "deadline", type: "uint256" },
    ],
    outputs: [{ name: "tokenOut", type: "uint256" }],
  },
  {
    type: "function",
    name: "sell",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenIn", type: "uint256" },
      { name: "minUsdcOut", type: "uint256" },
      { name: "recipient", type: "address" },
      { name: "deadline", type: "uint256" },
    ],
    outputs: [{ name: "usdcOut", type: "uint256" }],
  },
  {
    type: "function",
    name: "claimCreatorFees",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [{ name: "amount", type: "uint256" }],
  },
  {
    type: "function",
    name: "claimProtocolFees",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [{ name: "amount", type: "uint256" }],
  },
] as const;
